### ISSUE TITLE
Consuming Exiv2 with CMake

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#761]
I'm unable to get this work on 0.27-maintenance.  Clearly the cmake support files have moved from share to lib.  That's easy to change.

However, the code fails to compile for me and reports:
```
632 rmills@rmillsmm:~/gnu/github/exiv2/0.27-maintenance/exifprint $ make
Scanning dependencies of target exifprint
[ 50%] Building CXX object CMakeFiles/exifprint.dir/Users/rmills/gnu/github/exiv2/0.27-maintenance/samples/exifprint.cpp.o
/Users/rmills/gnu/github/exiv2/0.27-maintenance/samples/exifprint.cpp:5:10: fatal error: 'exiv2/exiv2.hpp' file not found
#include <exiv2/exiv2.hpp>
```

-----------------------------

The instructions in README.md are (and I'm sure they worked with 0.27). 

When exiv2 is installed, the files required to consume Exiv2 are installed in ${CMAKE_INSTALL_PREFIX}/lib/exiv2/cmake/

You can build samples/exifprint.cpp as follows:
```
$ cd <exiv2dir>
$ mkdir exifprint
$ cd    exifprint
$ *** EDIT CMakeLists.txt ***
$ cat CMakeLists.txt
cmake_minimum_required(VERSION 3.8)
project(exifprint VERSION 0.0.1 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_EXTENSIONS OFF)

find_package(exiv2 REQUIRED CONFIG NAMES exiv2)    # search ${CMAKE_INSTALL_PREFIX}/lib/exiv2/cmake/
add_executable(exifprint ../samples/exifprint.cpp) # compile this
target_link_libraries(exifprint exiv2)             # link exiv2

$ cmake .                                          # generate the makefile
$ make                                             # build the code
$ ./exifprint                                      # test your executable
Usage: ./exifprint [ file | --version || --version-test ]
$
```

**Comment by piponazo** [comment]
The last snippet looks strange since you are not pointing to the exiv2 installation dir when running CMake. You can find here a working example of how to consume exiv2:

https://github.com/piponazo/exiv2Consumer

**Comment by clanmills** [comment]
Brilliant, Luis.  The correct magic is to link _**`exiv2lib`**_ and not _`exiv2`_  
```
target_link_libraries(testApp exiv2lib)
```
So although find_package is looking for exiv2, we should be linking exiv2lib, and somehow that influences the compiler search path.

Thanks for your help.  Closed.  I'll update README.md tomorrow.

I will review all the effort your put into README-CONAN.md concerning cross-compiling.

Nehal and Andreas have moved exiv2.org to a new host.  Very pleased about that.
