### PR TITLE
Mingw instructions

### PR DESCRIPTION
**Pull request by piponazo**
In this PR I am providing a CMake Toolchain file which can be used to cross-compile Exiv2 from linux to windows with MinGW. There are also some minor tweaks here and there related to the cross-compilation process and some new documentation about it. 

Let me know if something is not clear or can be improved :wink:

### CODE REVIEW

File: README-CONAN.md [hunk 1]
```diff
@@ -320,9 +320,51 @@ Do not use conan on the Cygwin Platform.  To build Exiv2 for Cygwin use CMake wi
...
-Team Exiv2 supports MinGW msys/2.  Team Exiv2 does not support MinGW msys/1.0.
+We support:
+  - on Windows: MinGW msys/2.
+  - on Linux: MinGW toolchains.
+ 
+We do not support:
+  - on Windows: MinGW msys/1.0.
 
-As with Cygwin, we do not recommend using conan to build on the MinGW/msys2 platform.  We recommend installing dependences (expat, zlib) with platform tools or build/install from source.
+Dependencies can be installed with platform tools or conan.
```
Comment (D4N) [inline README-CONAN.md]: with platform tools => "with the platform's default tools" or "with the platform's tools"

File: README-CONAN.md [hunk 2]
```diff
@@ -320,9 +320,51 @@ Do not use conan on the Cygwin Platform.  To build Exiv2 for Cygwin use CMake wi
...
+
+#### Profiles for MinGW
+
+The profile linux-to-win64 is as follows:
```
Comment (D4N) [inline README-CONAN.md]: Could you add another sentence about this file? Something like "this is a cross compilation profile" etc.

File: README-CROSSCOMPILING.md [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+cross-compilation, we will have different sections for each of them.
+
+Something important to keep in mind is that since Exiv2 have some 3rd party dependencies, we would need to have
+such dependencies compiled for the target system. This can be normally achieved by installing system packages, 
+by using **conan**, or compiling them by yourselves.
+
+## CMake Toolchain files
+
+Exiv2 is configured through CMake and we can easily achieve cross-comilation via its toolchain files feature. The idea is to
+have different toolchain indicating to CMake where to find the tools to cross-compile the project (compiler, linker, etc).
```
Comment (D4N) [inline README-CROSSCOMPILING.md]: toolchain -> toolchains?

File: README-CROSSCOMPILING.md [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+We will place such files under `cmake/toolchain`.
+
+The most important step to remember is to use such toolchain file when running CMake for the first time to configure the
```
Comment (D4N) [inline README-CROSSCOMPILING.md]: such toolchain -> such a toolchain

File: README-CROSSCOMPILING.md [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+project (in a clean build directory). In case a CMake cache exists already in the build directory and you try to run
+cmake again with a different tooldchain file, things will probably go wrong.
```
Comment (D4N) [inline README-CROSSCOMPILING.md]: Please drop the probably, we don't want to tempt people ;-)

File: README-CROSSCOMPILING.md [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+
+### Linux-to-Win64
+
+Most of the linux distributions provide MinGW packages which provide a GCC compiler to cross-compile from linux to
```
Comment (D4N) [inline README-CROSSCOMPILING.md]: Most of the linux -> Many Linux, and later: linux -> Linux.

File: README-CROSSCOMPILING.md [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+windows. In some of these distributions there even exist mingw packages with popular libraries compiled for the target
+system (Windows). However, that is not always the case (For example, in Ubuntu 18.04 we cannot the expat package for
```
Comment (D4N) [inline README-CROSSCOMPILING.md]: The sentence in the brackets lacks a verb. I guess you forgot a "find"?

File: README-CROSSCOMPILING.md [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+MinGW).
+
+Nonetheless, with conan we can easily compile those 3rd party dependencies. You just need to have a proper profile
+as we explain in [README-CONAN.md](README-CONAN.md).
+
+The following code show the full process to compile Exiv2:
```
Comment (D4N) [inline README-CROSSCOMPILING.md]: show -> shows, compile -> cross compile

File: README-CROSSCOMPILING.md [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+conan install ../ --profile linux-to-win64 --build missing
+# Configure project to cross compile from linux to windows
+cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolschains/ubuntu-mingw64.cmake ../
+# Compile project
+cmake --build . --config Release
+```
+
+#### Required packages
+
+- Ubunut: `mingw-w64`.
```
Comment (D4N) [inline README-CROSSCOMPILING.md]: Ubunut -> Ubuntu

File: cmake/toolschains/ubuntu-mingw64.cmake [hunk 10]
```diff
@@ -0,0 +1,31 @@
...
+set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)
+
+# cross compilers to use for C and C++
+# Note: I had to use the posix variant to avoid compilation errors related with not finding the mutex class
+set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc-posix)
+set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++-posix)
+set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)
+
+# target environment on the build host system
+set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX} /usr/lib/gcc/${TOOLCHAIN_PREFIX}/7.3-posix)
```
Comment (D4N) [inline cmake/toolschains/ubuntu-mingw64.cmake]: Is there a way to not hardcode the gcc version?

File: contrib/vms/README.md [hunk 11]
```diff
@@ -28,9 +28,7 @@ distributions.
 For further details, consult the shell scripts `setup.sh` and
 `ci/install_dependencies.sh`.
 
-
-All boxes come with `conan` installed via pip in the `vagrant` user's home
```
Comment (D4N) [inline contrib/vms/README.md]: Why this change, did you touch the Vagrantfile?

**Review by D4N — CHANGES_REQUESTED** [review]
I've mostly commented on spelling/grammar. Overall the cross compilation document is pretty good and quite extensive, good job!

General suggestion: write names like "Linux", "Windows", or "MinGW" with the correct capitalization.

**Comment by D4N** [comment]
@piponazo Do you think it's worth it adding the cross compilation run that you described to GitLab?

File: cmake/toolschains/ubuntu-mingw64.cmake (hunk 10 above)
Comment (piponazo) [reply cmake/toolschains/ubuntu-mingw64.cmake]: Good point. Right now I cannot think about a way to do it. Nonetheless, since this toolchain is prepared for Ubuntu, and Ubuntu only has such version of MinGW I do not think it is very important  ...

Maybe we could rename the file to `ubuntu1804-mingw64.cmake` to be more specific about the platform where the toolchain can be used.

File: contrib/vms/README.md (hunk 11 above)
Comment (piponazo) [reply contrib/vms/README.md]: Because it was not true (At least I think so). We are not using conan in the boxes but instead we install the 3rd party libraries via the package manager of each system.

**Comment by piponazo** [comment]
> @piponazo Do you think it's worth it adding the cross compilation run that you described to GitLab?

I am not so sure. Now that we have the Fedora_MinGW job, the Ubuntu_MinGW one will not catch many other things not caught by that one. 

I would only do it in the future if we see that we really can catch new issues not identified with the current ones. I mostly proposed this PR as documentation for myself in the future 😛 (In case I need to help somebody with cross-compilation)

File: cmake/toolschains/ubuntu-mingw64.cmake (hunk 10 above)
Comment (D4N) [reply cmake/toolschains/ubuntu-mingw64.cmake]: > Maybe we could rename the file to ubuntu1804-mingw64.cmake to be more specific about the platform where the toolchain can be used.

That's a good idea, please do that!

File: contrib/vms/README.md (hunk 11 above)
Comment (D4N) [reply contrib/vms/README.md]: That's only partially correct, the vagrant boxes come with all the dependencies installed via the distributions package manager, but they also come with conan pre-installed (check this script out: `contrib/vms/setup_user.sh`).

I have added conan into the mix, so that anyone starting such a box has a full development environment with all pieces ready to go.

Comment (piponazo) [reply contrib/vms/README.md]: Ouch, I did not notice that. Sorry, I will revert this change.

**Comment by D4N** [comment]
> > @piponazo Do you think it's worth it adding the cross compilation run that you described to GitLab?
> 
> I am not so sure. Now that we have the Fedora_MinGW job, the Ubuntu_MinGW one will not catch many other things not caught by that one.
> 
> I would only do it in the future if we see that we really can catch new issues not identified with the current ones. I mostly proposed this PR as documentation for myself in the future stuck_out_tongue (In case I need to help somebody with cross-compilation)

I agree, my inner CI nerd was only seeing an opportunity to extend our pipeline :nerd_face:

**Comment by piponazo** [comment]
@D4N is there something missing for achieving your approval? 😛

**Comment by clanmills** [comment]
@piponazo I pulled down your text and looked at it.  I think it's OK for now.

I'd prefer to see the information in CROSS-COMPILING.md added to README-CONAN.md and then we have one document less.  And a short (one paragraph) note in README.md to say "Cross Compiling"  See README-CONAN.md.

When we arrive at v0.28, I'll review all our docs as I have done for v0.27 and v0.27.1.  In fact, it was in reviewing README.md that I discovered there was something wrong with "Consuming Exiv2 with CMake".

File: README-CONAN.md [hunk 12]
```diff
@@ -320,9 +320,52 @@ Do not use conan on the Cygwin Platform.  To build Exiv2 for Cygwin use CMake wi
...
+We do not support:
+  - on Windows: MinGW msys/1.0.
 
-As with Cygwin, we do not recommend using conan to build on the MinGW/msys2 platform.  We recommend installing dependences (expat, zlib) with platform tools or build/install from source.
+Dependencies can be installed with the platform's default tools or conan.
+
+#### Profiles for MinGW
+
+Profiles for cross-compilation are a bit special and you can find more information about them [here](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html?highlight=cross%20compiling).
+The profile `linux-to-win64` we use for compiling from Ubuntu to Win64 is as follows:
```
Comment (D4N) [inline README-CONAN.md]:
```suggestion
The profile `linux-to-win64` which we use for compiling from Ubuntu to Win64 is as follows:
```

File: README-CROSSCOMPILING.md [hunk 13]
```diff
@@ -0,0 +1,67 @@
+# Cross-compilation
+
+In this document we provide some guidelines to cross-compile Exiv2. Since there could be several ways to achieve
+cross-compilation, we will have different sections for each of them.
+
+Something important to keep in mind is that since Exiv2 have some 3rd party dependencies, we would need to have
```
Comment (D4N) [inline README-CROSSCOMPILING.md]:
```suggestion
Something important to keep in mind is that since Exiv2 has some 3rd party dependencies, we need to have
```

File: README-CROSSCOMPILING.md [hunk 14]
```diff
@@ -0,0 +1,67 @@
...
+In file included from /media/linuxDev/programming/exiv2/include/exiv2/xmp_exiv2.hpp:35:0,
+                 from /media/linuxDev/programming/exiv2/include/exiv2/image.hpp:33,
+                 from /media/linuxDev/programming/exiv2/src/tiffimage_int.hpp:34,
+                 from /media/linuxDev/programming/exiv2/src/cr2header_int.hpp:32,
+                 from /media/linuxDev/programming/exiv2/src/cr2header_int.cpp:1:
+/media/linuxDev/programming/exiv2/include/exiv2/properties.hpp:215:21: error: ‘mutex’ in namespace ‘std’ does not name a type
+         static std::mutex mutex_;
+```
+
+It can be probably caused because you are not using the right variant of the MinGW compiler in the toolchain file.
```
Comment (D4N) [inline README-CROSSCOMPILING.md]:
```suggestion
It is probably caused by using the wrong variant of the MinGW compiler in the toolchain file.
```

File: cmake/toolschains/ubuntu1804-mingw64.cmake [hunk 15]
```diff
@@ -0,0 +1,31 @@
...
+set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)
+
+# cross compilers to use for C and C++
+# Note: I had to use the posix variant to avoid compilation errors related with not finding the mutex class
+set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc-posix)
+set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++-posix)
+set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)
+
+# target environment on the build host system
+set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX} /usr/lib/gcc/${TOOLCHAIN_PREFIX}/7.3-posix)
```
Comment (D4N) [inline cmake/toolschains/ubuntu1804-mingw64.cmake]: Question: in README-crosscompiling you mentioned that an error can appear when the mingw-win32 compiler is used. But here posix is hardcoded, so that issue shouldn't be possible, right? (provided people actually use our toolchain file)

File: contrib/vms/README.md [hunk 16]
```diff
@@ -29,9 +29,7 @@ For further details, consult the shell scripts `setup.sh` and
 `ci/install_dependencies.sh`.
 
 
-All boxes come with `conan` installed via pip in the `vagrant` user's home
-directory and the `exiv2` git repository cloned.
```
Comment (D4N) [inline contrib/vms/README.md]: This line is still missing.

**Review by D4N — CHANGES_REQUESTED** [review]
There's only a few small things that I stumbled over, overall pretty good!

File: cmake/toolschains/ubuntu1804-mingw64.cmake (hunk 15 above)
Comment (piponazo) [reply cmake/toolschains/ubuntu1804-mingw64.cmake]: Exactly, this toolchain should always work on Ubuntu 18.04. The comment in the file `README-crosscompiling.md` is a general statement that could be helpful for people trying to write toolchain files for other linux distributions or Ubuntu versions.

**Review by D4N — APPROVED** [review]
Thanks for your patience, looks good now.
