### ISSUE TITLE
Trigger Linux-Distributions jobs on PRs

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#2100]
##### **Is your feature request related to a problem?**
I noticed that the "Nightly - Linux Distributions" builds is failing on the `main` branch after merging #2090. However, in that PR all the CI checks were passing.

##### **Describe the solution you would like**
It would be good to also trigger the "Linux Distributions" builds in PRs, so that we do not end up breaking something in `mian` without noticing in the PRs.

We would just need to change `.github/workflows)/nightly_Linux_distributions.yml` so that it runs on PRs.

Furthermore, we should fix the current issue on `main`. It is complaining about undefined references to `std::filesystem`:

```bash
[100%] Linking CXX executable ../bin/exiv2
CMakeFiles/exiv2.dir/actions.cpp.o: In function `(anonymous namespace)::metacopy(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool)':
actions.cpp:(.text+0xa4e7): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
actions.cpp:(.text+0xa4f7): undefined reference to `std::filesystem::temp_directory_path[abi:cxx11]()'
actions.cpp:(.text+0xa50f): undefined reference to `std::filesystem::__cxx11::path::has_root_directory() cons
...
```

Something like [this](https://stackoverflow.com/a/54290445/1977218) should work.

**Comment by hassec** [comment]
Running the entire workflow on PRs might be a lot. (It's 48 builds)   
But I do think it makes sense to have a build of one of the older distros in the PR pipeline :+1:

**Comment by piponazo** [comment]
I agree that it might be intimidating to have so many CI stuff in PRs , but it is actually one of the CI pipelines that take less time:

![image](https://user-images.githubusercontent.com/102645/154015732-a6ca2469-fddf-482c-af3e-1a67626877ab.png)

It takes half of the time that the "Windows Matrix" pipeline last. And if the CI pipelines run in parallel we should not get any delay.

**Comment by hassec** [comment]
I didn't realize that pipeline was that quick. That's way quicker than many of the windows pipelines :sweat_smile:       
In that case :+1: from me
