### ISSUE TITLE
error: 'EXIV2API' does not name a type

### ISSUE THREAD

**Issue by mardy** [Exiv2/exiv2#636]
The `convert.hpp` file should include `exiv2lib_export.h`. Otherwise, this occurs:

```
In file included from /builds/mardy/imaginario/src/metadata.cpp:26:0:
/builds/mardy/imaginario/staging/include/exiv2/convert.hpp:53:5: error: 'EXIV2API' does not name a type
     EXIV2API void copyExifToXmp(const ExifData& exifData, XmpData& xmpData);
     ^
/builds/mardy/imaginario/staging/include/exiv2/convert.hpp:55:5: error: 'EXIV2API' does not name a type
     EXIV2API void moveExifToXmp(ExifData& exifData, XmpData& xmpData);
     ^
/builds/mardy/imaginario/staging/include/exiv2/convert.hpp:58:5: error: 'EXIV2API' does not name a type
     EXIV2API void copyXmpToExif(const XmpData& xmpData, ExifData& exifData);
     ^
...
```

**Comment by mardy** [comment]
This worked fine until 0.26. Then 6ba4081f95e24c52163d266a4a6e1391088f6bc5 broke it.

**Comment by mardy** [comment]
1. I tried Ubuntu with both g++ 4.5 and 8.1, but by looking at the code I bet that this happens on any platform: if a program includes `convert.hpp` as the first exiv2 header, it will get this error.

2. Yes, I think that that would fix it.

**Comment by clanmills** [comment]
Thanks for the update. 

This change was introduced in September 2018 and since then I've built Exiv2 thousands of times on Ubuntu, MacOS-X, Cygwin, MinGW/msys2 and msvc and never seen this.  So, while I believe you, you can understand why I am surprised.

When you're writing your own code, please follow the pattern in our samples and use `#include <exiv2/exiv2.hpp>` to "pull in" the Exiv2 API.  Don't include header files directly in your code.

Thank you for providing a work-around that fixes this for you.  I built on MacOS-X with your change and everything build in the usual way.  I expect we'll adopt you fix, however I'm interested to hear the thoughts of @piponazo as he is our CMake expert.

**Comment by piponazo** [comment]
This is a real issue and as @mardy pointed out, it was introduced in 6ba4081f95e24c52163d266a4a6e1391088f6bc5. 

While the exiv2 suggestion is to include `exiv2.hpp` I can understand that some people prefers to use only what is needed (I actually think also in this way). The problem is that `convert.hpp` is not including the file automatically generated by CMake: `exiv2lib_export.h`.

I'll create a PR this afternoon to fix the situation.
