### PR TITLE
cmake: simplify libintl check

### PR DESCRIPTION
**Pull request by bkuhls**
According to https://cmake.org/cmake/help/v3.4/module/FindIntl.html
the FindIntl module already checks for libintl.so.

### CODE REVIEW

**Comment by bkuhls** [comment]
The previous fixes did not work out for buildroot in all cases as well, this patch fixed the remaining buildroot problem, please test on Cygwin/MacOSX & Co.

**Comment by clanmills** [comment]
@bkuhls I fixed this a couple of hours ago and tested it on Cygwin/Linux/MacOS-X.

**Comment by clanmills** [comment]
@bkuhls I've added your code INCLUDE_DIRECTORIES(${Intl_INCLUDE_DIRS}) Thank You very much for this suggestion.

**Comment by bkuhls** [comment]
With current git HEAD as of 4e86c1d61c4b8ab2cbbb31db0031b8e1d1872231 the buildroot build still failed without this patch:
```
[100%] Linking CXX executable ../bin/exiv2
CMakeFiles/exiv2.dir/exiv2.cpp.o: In function `main':
exiv2.cpp:(.text.startup+0x1f0): undefined reference to `libintl_bindtextdomain'
exiv2.cpp:(.text.startup+0x1f8): undefined reference to `libintl_bindtextdomain'
exiv2.cpp:(.text.startup+0x200): undefined reference to `libintl_textdomain'
exiv2.cpp:(.text.startup+0x204): undefined reference to `libintl_textdomain'
libexiv2.so.26.0.0: undefined reference to `libintl_dgettext'

```
PS: I will try 88cf58613ffde4c907011bea82f61daae6006c3c now and will report back.

**Comment by bkuhls** [comment]
Build is still broken with 88cf58613ffde4c907011bea82f61daae6006c3c, I will send a rebased version of this patch
```
[ 98%] Linking CXX executable ../bin/remotetest
libexiv2.so.26.0.0: undefined reference to `libintl_dgettext'
libexiv2.so.26.0.0: undefined reference to `libintl_bindtextdomain'
[100%] Linking CXX executable ../bin/exiv2
CMakeFiles/exiv2.dir/exiv2.cpp.o: In function `main':
exiv2.cpp:(.text.startup+0x1f0): undefined reference to `libintl_bindtextdomain'
exiv2.cpp:(.text.startup+0x1f8): undefined reference to `libintl_bindtextdomain'
exiv2.cpp:(.text.startup+0x200): undefined reference to `libintl_textdomain'
exiv2.cpp:(.text.startup+0x204): undefined reference to `libintl_textdomain'
libexiv2.so.26.0.0: undefined reference to `libintl_dgettext'
```

**Comment by clanmills** [comment]
I have to go out for 3 hours this morning (and later today).  We'll get this fixed today.  Thanks for your help.

**Comment by bkuhls** [comment]
rebased patch force-pushed to branch

**Comment by clanmills** [comment]
@bkuhls 

I'm new to git and have no idea what the expression "rebased patch force-pushed to branch" means, however I've accepted your patch and it's working fine on MacOS-X/Linux/Cygwin.  Very good work.  Thank you very much.  I'll test/fix on MSVC.
