### ISSUE TITLE
exiv2 0.26 build failure on older OS X systems

### ISSUE THREAD

**Issue by Schamschula** [Exiv2/exiv2#9]
On older (Mac) OS X systems (pre 10.7) the build fails with:

`:info:build [ 54%] Building CXX object src/CMakeFiles/exiv2.dir/actions.cpp.o
:info:build cd /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_graphics_exiv2/exiv2/work/exiv2-trunk/src && /usr/bin/g++-4.2  -DEXV_HAVE_DLL -DEXV_HAVE_STDINT_H -DEXV_LOCALEDIR=\"/opt/local/share/locale\" -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_graphics_exiv2/exiv2/work/exiv2-trunk/src -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_graphics_exiv2/exiv2/work/exiv2-trunk/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_graphics_exiv2/exiv2/work/exiv2-trunk/include/exiv2 -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_graphics_exiv2/exiv2/work/exiv2-trunk -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_graphics_exiv2/exiv2/work/exiv2-trunk/xmpsdk/include -I/opt/local/include  -pipe -Os -DNDEBUG -arch ppc -mmacosx-version-min=10.5   -std=c++98 -o CMakeFiles/exiv2.dir/actions.cpp.o -c /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_graphics_exiv2/exiv2/work/exiv2-trunk/src/actions.cpp
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_graphics_exiv2/exiv2/work/exiv2-trunk/src/actions.cpp:2050: error: ‘PTHREAD_RECURSIVE_MUTEX_INITIALIZER’ was not declared in this scope
`

Also see https://trac.macports.org/ticket/54335

**Comment by clanmills** [comment]
Thanks for letting me know about this.

I'm a little surprised as I occasionally build on Tiger (10.4) with GCC 4.0.  I do this because I have an ancient 2003 PowerBook and it's the only big-endian machine to which I have access!  The symbol PTHREAD_RECURSIVE_MUTEX_INITIALIZER is used in actions.cpp to provide a mutex/critical_section to ensure that temporaryPath() returns unique pathnames.

I'll have a look at this on Tiger tomorrow (2017-06-20).

**Comment by clanmills** [comment]
Gentlemen

I reproduced this and fixed this on Tiger.  I've also update our release procedure to explicitly mention build/test on Tiger in future.  This was a bug that was allowed to escape and could have been detected.  Such a lot to do during the release, it's easy to forget something that isn't on the Checklist.

**Comment by awilfox** [comment]
For what it's worth, this is also necessary for building with the musl libc on Linux.  I am glad this is already handled for next release :+1:

**Comment by awilfox** [comment]
Ah actually I spoke too soon, this only fixes it for the case where `__APPLE__` is defined.  This also needs to be done on Linux since the musl libc does not define any static `PTHREAD_RECURSIVE*` initialisers.
