### ISSUE TITLE
Exiv2 and Qt

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#714]
Exiv2 v0.26 brought support for MinGW/msys1.0/32.  The test suite included code to build/link a simple command-line program with qmake.  This took a considerable effort which I won't describe now, however I concluded that we should deprecate this in v0.27.

I was encouraged to adopt MinGW/msys2 for v0.27 by _**darktable**_.  We successfully build and run the test suite with Exiv2 v0.27 and this is documented in README.md  

However, we received the following report in May 2018 that MinGW/Qt wasn't working and I concluded it was to do with C++11 which _at the time_ we expected to deliver with Exiv2 v0.27.0   http://dev.exiv2.org/boards/3/topics/3139?r=3148#message-3148 

I have enjoyed an email discussion with a user about this.  I'm unable to get MinGW/Qt/Exiv2 v0.27 to compile and/or link.  I have _**NOT **_ looked at Qt+Exiv2 on MacOS-X or Linux or MSVC. 

When building application with QtCreator (and/or qmake) using Qt 5.12 (64 bit) the error message is:
```
.../exiv2-test/main.cpp:51: undefined reference to `__imp__ZN5Exiv213versionStringB5cxx11Ev'
```

The compiler is looking the c++11 version of `Exiv2::versionString' which isn't in our C++98 library.

So, I've backed up to earlier editions of Qt which build 32 bit and I believe build for C++98.  I tried to link our 32 bit build with Qt (5.1)  It doesn’t link.  The error is similar to the 64 bit errors (concerning versionString etc).

So, I tried to build exiv2 with the toolchain in c:\Qt\Tools\mumble_jumble\bin:
32bits: mumble_jumble=mingw48_32 (Qt 5.1)
64bits: mumble_jumble=mingw73_64 (Qt 5.12.1)

Exiv2 will not compile with the headers provided on the Qt/toolchain.
32bits: can’t remember.  Goes crazy.
64bits: error: 'sched_yield() was not declared in this scope’

This has something to do with the threads.  Exiv2 uses pthreads, and I thought Qt also uses them.

My feeling is that getting this to work will take a lot of effort.  There are lots of different versions of Qt (5.1 through 5.12) with different tool-chains. (4.8, 4.9, 7.3).

Because I have hitherto used (and liked) Qt, I would like to see Qt/Exiv2 working together.  And, I believe it will work.  The challenge is to compile and link the code and don't believe the code requires change.  However, last year's diagnosis _**requires C++11**_ may be correct and Exiv2 v0.27 will never work with Qt.

I believe @cgilles cross compiles for MinGW to distribute DigiKam on Windows and may be able to offer suggestions. 

To make the v0.27.1 schedule on 2019-03-31, I want to avoid spending more time on Qt (on any platform).  I have already spent about 8 hours investigating on behalf of the user who raised this matter.

**Comment by cgilles** [comment]
Le dim. 24 févr. 2019 à 20:23, Robin Mills <notifications@github.com> a
écrit :

> Exiv2 v0.26 brought support for MinGW/msys1.0/32. The test suite included
> code to build/link a simple command-line program with qmake. This took a
> considerable effort which I won't describe now, however I concluded that we
> should deprecate this in v0.27.
>
> I was encouraged to adopt MinGW/msys2 for v0.27 by *darktable*. We
> successfully build and run the test suite with Exiv2 v0.27 and this is
> documented in README.md
>
> However, we received the following report in May 2018 that MinGW/Qt wasn't
> working and I concluded it was to do with C++11 which *at the time* we
> expected to deliver with Exiv2 v0.27.0
> http://dev.exiv2.org/boards/3/topics/3139?r=3148#message-3148
>
> I have enjoyed an email discussion with a user about this. I'm unable to
> get MinGW/Qt/Exiv2 v0.27 to compile and/or link. I have ***NOT *** looked
> at Qt+Exiv2 on MacOS-X or Linux or MSVC.
>
> When building application with QtCreator (and/or qmake) using Qt 5.12 (64
> bit) the error message is:
>
> .../exiv2-test/main.cpp:51: undefined reference to `__imp__ZN5Exiv213versionStringB5cxx11Ev'
>
>
> The compiler is looking the c++11 version of `Exiv2::versionString' which
> isn't in our C++98 library.
>
> So, I've backed up to earlier editions of Qt which build 32 bit and I
> believe build for C++98. I tried to link our 32 bit build with Qt (5.1) It
> doesn’t link. The error is similar to the 64 bit errors (concerning
> versionString etc).
>
> So, I tried to build exiv2 with the toolchain in
> c:\Qt\Tools\mumble_jumble\bin:
> 32bits: mumble_jumble=mingw48_32 (Qt 5.1)
> 64bits: mumble_jumble=mingw73_64 (Qt 5.12.1)
>
> Exiv2 will not compile with the headers provided on the Qt/toolchain.
> 32bits: can’t remember. Goes crazy.
> 64bits: error: 'sched_yield() was not declared in this scope’
>
> This has something to do with the threads. Exiv2 uses pthreads, and I
> thought Qt also uses them.
>
> My feeling is that getting this to work will take a lot of effort. There
> are lots of different versions of Qt (5.1 through 5.12) with different
> tool-chains. (4.8, 4.9, 7.3).
>
> Because I have hitherto used (and liked) Qt, I would like to see Qt/Exiv2
> working together. And, I believe it will work. The challenge is to compile
> and link the code and don't believe the code requires change. However, last
> year's diagnosis *requires C++11* may be correct and Exiv2 v0.27 will
> never work with Qt.
>
> I believe @cgilles <https://github.com/cgilles> cross compiles for MinGW
> to distribute DigiKam on Windows and may be able to offer suggestions.
>
Ahaha.. YES !

and WE USE MXE to cross-compile all : low level libraries, Whole Qt 5 (5.12
currently in MXE packages), whole KF5 libraries (all based on Qt5), whole
digiKam (all based on Qt5, the installer (MSIS).

So, the MinGW support with Qt5 is just Excellent. And MXE cross compilation
framework is just a rock.

I use it since 4 year now with digiKam, and MXE packages are impressive.

Exiv2 package exists in MXE. It's a little bit outdated. Just ask to MXE
team to update the config file for this packages.

Personalty, i cross compile Exiv2 in 32 and 64 bits using official tarball
for stable digiKam releases, and with git/master code for beta releases.

So for me, this mail is just incomprehensible...

Best

Gilles

>

**Comment by D4N** [comment]
Since MXE works for @cgilles and no one else complained about Qt5, I'll close this.

If there are objections, please either reopen this issue or complain (if you can't reopen it).

**Comment by Minganie** [comment]
I'm actually the one who originally encountered this issue and asked @clanmills about it. Sorry for the noob question but... what is MXE? I didn't quite understand @cgilles 's solution/workaround...

**Comment by cgilles** [comment]
MXE is a package manager for Windows, based on MinGW toolchain. The goal is to be able to cross compile for a Windows target, under Linux or MacOS.

 As we target digiKam for Windows since a while, i experimented a lots of solutions to build an installer for Windows. I tried plenty of packaging, mostly based on Microsoft complier. But not are really perfect, excepted MXE, that i discovered while a developper meting between KDE teams. One project, named Krita, an advanced image editor based on Qt toolkit has experiment the Windows packaging with MXE.

The advantage of MXE : you don't need Windows from start to end. ALL is cross compiled under Linux, including all low level dependencies. This take age, but the result is impressive. Qt framework is very well supported and all components are available (5.12 version).

I use also MXE in my office, to cross compile for Windows a large framework that i developed with Qt and it's work like a charm.

Take a look to the project page for the list of packages available : 

https://mxe.cc/

**Comment by Minganie** [comment]
So... that means to use MXE one must work under Linux then? So you develop under Linux and then use MXE to create an exe for use in Windows?  That does sound extremely useful, but does not solve my use case: develop a Qt application using Exiv2 under Windows for use in Windows.

**Comment by clanmills** [comment]
Exactly.  We're wondered off into the long grass.

On the recommendation of @cgilles, I tried MXE in December.  It consumed about 20GBytes of disk space, took more than 24 hours to install and after installing, wouldn't build anything.

However, MXE installs more-or-less the same tools (GCC etc), CMake and Qt.  So, it's proof that Qt/Exiv2 v0.27 applications can be build for MinGW.

**Comment by Minganie** [comment]
Okay. Qt/Exiv2 0.27 *can* be built for MinGW - but I'm not sure how. Does that mean I should download exiv2 source and attempt to build it with mingw? Or MSVS (I only have access to Community)? Or should we reopen this ticket?

**Comment by cgilles** [comment]
Robin,

>On the recommendation of @cgilles, I tried MXE in December. It consumed about 20GBytes of disk >space, took more than 24 hours to install and after installing, wouldn't build anything.

It's because you start to build whole MXE packages without control. You only few one to build Exiv2, and this take only 20min on my computer if you use the bash script that i shared with out in December...

**Comment by D4N** [comment]
@Minganie Can you please open a new issue on Github and describe there what you want to achieve and which problems you ran into? Then we can search for a solution.
